# Generated by Django 5.1.4 on 2024-12-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('year_study', models.CharField(max_length=10)),
                ('phone_number', models.BigIntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='street',
            name='Chairperson',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Street',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_owner', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('st_reg_no', models.CharField(max_length=100)),
                ('date_uploaded', models.IntegerField()),
                ('project_file', models.FileField(upload_to='projects/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crsapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Chairperson',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
