# Generated by Django 5.1.4 on 2024-12-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0002_instructor_student_remove_street_chairperson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_owner',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
