# Generated by Django 5.1.4 on 2024-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0004_rename_name_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_uploaded',
            field=models.DateField(),
        ),
    ]
