# Generated by Django 5.1.4 on 2024-12-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0005_alter_project_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AlterField(
            model_name='project',
            name='st_reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
