# Generated by Django 5.1.4 on 2024-12-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0006_remove_project_student_alter_project_st_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
