# Generated by Django 5.1.4 on 2024-12-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0007_student_image_alter_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
