# Generated by Django 5.1.4 on 2024-12-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0008_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
