# Generated by Django 5.1.4 on 2024-12-22 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0009_alter_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_craeted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
