# Generated by Django 5.1.4 on 2024-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0010_student_date_craeted_alter_project_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
