# Generated by Django 5.1.4 on 2024-12-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0012_remove_student_id_alter_project_st_reg_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='st_reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crsapp.student'),
        ),
    ]
