# Generated by Django 5.1.4 on 2024-12-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0013_alter_project_st_reg_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='st_reg_no',
            new_name='reg_no',
        ),
    ]
