# Generated by Django 5.1.4 on 2024-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0014_rename_st_reg_no_project_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
