# Generated by Django 5.1.4 on 2024-12-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0015_alter_student_reg_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='reg_no',
            new_name='Student',
        ),
    ]
