# Generated by Django 5.1.4 on 2024-12-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0016_rename_reg_no_project_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Student',
            new_name='reg_no',
        ),
    ]
